name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
